# Generated by Django 3.1.4 on 2020-12-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('birthday', models.DateField()),
                ('mailing_check', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.URLField(default='https://i0.wp.com/prikachi.com/wp-content/uploads/2020/07/DPP1.jpg', max_length=512)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
