# Generated by Django 3.1.4 on 2021-01-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('birthday', models.DateField(null=True)),
                ('mailing_check', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.URLField(default='https://pbs.twimg.com/profile_images/1109389733912666112/XX55fTPf.jpg', max_length=512)),
                ('bookmarks', models.ManyToManyField(related_name='bookmark_users', through='bookmarks.BookMark', to='homes.Home')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=32)),
                ('is_valid', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('commission_date', models.DateTimeField(auto_now_add=True)),
                ('is_superhost', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_host', to='homes.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_host', to='users.user')),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
