# Generated by Django 3.1.4 on 2021-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210105_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://cdn.iconscout.com/icon/free/png-512/github-153-675523.png', max_length=512),
        ),
    ]
