# Generated by Django 3.1.3 on 2020-12-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationguest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cvc',
        ),
    ]
