# Generated by Django 3.1.4 on 2020-12-30 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'building_types',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'facility_types',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('capacity_guest', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=64)),
                ('latitude', models.FloatField(default='127.03130')),
                ('longitude', models.FloatField(default='37.30225')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.buildingtype')),
            ],
            options={
                'db_table': 'homes',
            },
        ),
        migrations.CreateModel(
            name='HomeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homes.home')),
            ],
            options={
                'db_table': 'homes_rooms',
            },
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'home_types',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'rule_types',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.ruletype')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.bed')),
                ('home_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.homeroom')),
            ],
            options={
                'db_table': 'rooms_beds',
            },
        ),
        migrations.CreateModel(
            name='HomeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(null=True)),
                ('check_out', models.TimeField(null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.rule')),
            ],
            options={
                'db_table': 'homes_rules',
            },
        ),
        migrations.CreateModel(
            name='HomePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.price')),
            ],
            options={
                'db_table': 'homes_prices',
            },
        ),
        migrations.CreateModel(
            name='HomeOpiton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.option')),
            ],
            options={
                'db_table': 'homes_options',
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homes.home')),
            ],
            options={
                'db_table': 'home_images',
            },
        ),
        migrations.CreateModel(
            name='HomeFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.facility')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
            ],
            options={
                'db_table': 'home_facilities',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='facility',
            field=models.ManyToManyField(through='homes.HomeFacility', to='homes.Facility'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.hometype'),
        ),
        migrations.AddField(
            model_name='home',
            name='option',
            field=models.ManyToManyField(through='homes.HomeOpiton', to='homes.Option'),
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.ManyToManyField(through='homes.HomePrice', to='homes.Price'),
        ),
        migrations.AddField(
            model_name='home',
            name='region',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='homes.region'),
        ),
        migrations.AddField(
            model_name='home',
            name='rule',
            field=models.ManyToManyField(through='homes.HomeRule', to='homes.Rule'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.facilitytype'),
        ),
    ]
