# Generated by Django 3.1.4 on 2021-01-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('users', '0001_initial'),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='homerule',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
        migrations.AddField(
            model_name='homerule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.rule'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homes.home'),
        ),
        migrations.AddField(
            model_name='homeprice',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
        migrations.AddField(
            model_name='homeprice',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.pricecategory'),
        ),
        migrations.AddField(
            model_name='homeopiton',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
        migrations.AddField(
            model_name='homeopiton',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.option'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homes.home'),
        ),
        migrations.AddField(
            model_name='homefacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.facility'),
        ),
        migrations.AddField(
            model_name='homefacility',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
        migrations.AddField(
            model_name='home',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.buildingtype'),
        ),
        migrations.AddField(
            model_name='home',
            name='facility',
            field=models.ManyToManyField(through='homes.HomeFacility', to='homes.Facility'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.hometype'),
        ),
        migrations.AddField(
            model_name='home',
            name='option',
            field=models.ManyToManyField(through='homes.HomeOpiton', to='homes.Option'),
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.ManyToManyField(through='homes.HomePrice', to='homes.PriceCategory'),
        ),
        migrations.AddField(
            model_name='home',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='homes.region'),
        ),
        migrations.AddField(
            model_name='home',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewed_homes', through='homes.Review', to='users.User'),
        ),
        migrations.AddField(
            model_name='home',
            name='rule',
            field=models.ManyToManyField(through='homes.HomeRule', to='homes.Rule'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.facilitytype'),
        ),
    ]
