# Generated by Django 3.1.4 on 2020-12-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bookmarks'),
        ('homes', '0002_auto_20201230_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewed_homes', through='homes.Review', to='users.User'),
        ),
    ]
