# Generated by Django 3.1.4 on 2020-12-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20201230_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='homes.region'),
        ),
    ]
