# Generated by Django 3.1.4 on 2020-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20201230_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='around_m',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='zoom_level',
            field=models.IntegerField(default=13),
        ),
    ]
