# Generated by Django 3.1.3 on 2020-12-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20201230_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PriceCategory',
        ),
        migrations.RenameField(
            model_name='homeprice',
            old_name='price',
            new_name='price_category',
        ),
        migrations.RemoveField(
            model_name='region',
            name='around_m',
        ),
        migrations.AlterField(
            model_name='home',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=127.0313, max_digits=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=37.30225, max_digits=15),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=127.0313, max_digits=15),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=37.30225, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='pricecategory',
            table='price_categories',
        ),
    ]
