# Generated by Django 3.1.3 on 2020-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20201230_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='around_radius_m',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
