# Generated by Django 3.1.3 on 2020-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_region_around_radius_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=127.0313, max_digits=9),
        ),
        migrations.AlterField(
            model_name='home',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=37.30225, max_digits=9),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=127.0313, max_digits=9),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=37.30225, max_digits=9),
        ),
    ]
