# Generated by Django 3.1.4 on 2021-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_auto_20201230_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon_url',
            field=models.URLField(null=True),
        ),
    ]
