# Generated by Django 3.1.4 on 2021-01-04 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_payment_cvc'),
        ('homes', '0009_facility_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
            preserve_default=False,
        ),
    ]
